### ISSUE TITLE
hello dalao

### ISSUE THREAD

**Issue by lijiajun3029** [Sunwc0/vegetable_fruit_imageRe#2]
the lables list in validate.py  is different from the lables list in tfrecord.py? why?
I am a new player, please help me , if not ,I still thank you ,I will slowly read source .
thanks!

**Comment by Sunwc0** [comment]
这个项目当时做的比较粗糙，将样本图片转为tfrecord的时候是按照读取data中的顺序来处理的，你转的时候打印下，这样validate.py中的label数组的顺序就会和tfrecord中一样了
