### ISSUE TITLE
new.train时报错

### ISSUE THREAD

**Issue by SuperMisswei** [Sunwc0/vegetable_fruit_imageRe#3]
您好，我在运行new.train时报错，不清楚为何要使用线程，将训练数据转换成train.tfrecords之后怎么用new.train训练哦，卡在这里动不了，need help。

**Comment by SuperMisswei** [comment]
训练数据测试数据的读取都是正确的，在运行sess.run的时候直接跳出报错了

**Comment by Sunwc0** [comment]
这个版本可能比较老了，报错信息给一下我看下是啥问题

**Comment by SuperMisswei** [comment]
没遇到过这是什么错误
------------------ 原始邮件 ------------------
发件人: "孙万聪"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 中午11:26
收件人: "Sunwc0/vegetable_fruit_imageRe"<vegetable_fruit_imageRe@noreply.github.com>;
抄送: "风掠无影wsj"<weishaojie1995.com@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Sunwc0/vegetable_fruit_imageRe] new.train时报错 (#3)




这个版本可能比较老了，报错信息给一下我看下是啥问题

**Comment by Sunwc0** [comment]
用tf.train.Coordinator()的原因是为了方便读数据，并在数据读完之后正确的关闭队列，看while的那个循环，你用的tf是什么版本，然后把具体的报错的error信息给我看下

**Comment by SuperMisswei** [comment]
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[30,64,147,147] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator cuda_host_bfc
	 [[Node: swap_out_gradients/InceptionResnetV2/InceptionResnetV2/Conv2d_2b_3x3/Relu_grad/ReluGrad_1 = _CopyFromGpuToHost[T=DT_FLOAT, _class=["loc@gradie...ReluGrad_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](InceptionResnetV2/InceptionResnetV2/Conv2d_2b_3x3/Relu)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.




During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "E:/project/vegetables/vegetable_fruit_imageRe-master/model/new_train.py", line 76, in <module>
    sess.run(optimizer, feed_dict={x_train: image, y_train: label, is_training: True})
  File "E:\Anaconda3\envs\keras2.1.6\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "E:\Anaconda3\envs\keras2.1.6\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Anaconda3\envs\keras2.1.6\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "E:\Anaconda3\envs\keras2.1.6\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[30,64,147,147] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator cuda_host_bfc
	 [[Node: swap_out_gradients/InceptionResnetV2/InceptionResnetV2/Conv2d_2b_3x3/Relu_grad/ReluGrad_1 = _CopyFromGpuToHost[T=DT_FLOAT, _class=["loc@gradie...ReluGrad_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](InceptionResnetV2/InceptionResnetV2/Conv2d_2b_3x3/Relu)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.




During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "E:/project/vegetables/vegetable_fruit_imageRe-master/model/new_train.py", line 105, in <module>
    coord.join(threads)
  File "E:\Anaconda3\envs\keras2.1.6\lib\site-packages\tensorflow\python\training\coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "E:\Anaconda3\envs\keras2.1.6\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "E:\Anaconda3\envs\keras2.1.6\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "E:\Anaconda3\envs\keras2.1.6\lib\site-packages\tensorflow\python\client\session.py", line 1205, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "E:\Anaconda3\envs\keras2.1.6\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[Node: get_batch_1/decode_from_tfrecord/sub/_51 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_16_get_batch_1/decode_from_tfrecord/sub", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]



这是运行之后报的异常，我看不懂
------------------ 原始邮件 ------------------
发件人: "孙万聪"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 下午3:11
收件人: "Sunwc0/vegetable_fruit_imageRe"<vegetable_fruit_imageRe@noreply.github.com>;
抄送: "风掠无影wsj"<weishaojie1995.com@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Sunwc0/vegetable_fruit_imageRe] new.train时报错 (#3)




用tf.train.Coordinator()的原因是为了方便读数据，并在数据读完之后正确的关闭队列，看while的那个循环，你用的tf是什么版本，然后把具体的报错的error信息给我看下

**Comment by Sunwc0** [comment]
看情况你用的不是tensorflow而是keras，我没用过不知道tf的APIkeras是否兼容的很好

**Comment by SuperMisswei** [comment]
我是在有keras的环境下跑的，但是代码没有调用keras的框架啊，感觉是在读取数据的时候由于内存问题跳出了线程，我没有用过多线程。我在keras下跑的时候也是尺寸超过128*128就报错了，感觉对数据的shape和跑网络的数据变化不理解。




------------------ 原始邮件 ------------------
发件人: "孙万聪"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 下午3:44
收件人: "Sunwc0/vegetable_fruit_imageRe"<vegetable_fruit_imageRe@noreply.github.com>;
抄送: "风掠无影wsj"<weishaojie1995.com@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Sunwc0/vegetable_fruit_imageRe] new.train时报错 (#3)




看情况你用的不是tensorflow而是keras，我没用过不知道tf的APIkeras是否兼容的很好

**Comment by Sunwc0** [comment]
你尝试下把batch_size调小一点试一下，inception_resnet_v2网络的输入必须是299x299大小3通道的图片，如果不是也会报错

**Comment by SuperMisswei** [comment]
嗯嗯 我试一下，这个inception_resnet_v2训练完之后为什么还要用aliyun训练，没懂写了两个训练代码




------------------ 原始邮件 ------------------
发件人: "孙万聪"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 下午3:55
收件人: "Sunwc0/vegetable_fruit_imageRe"<vegetable_fruit_imageRe@noreply.github.com>;
抄送: "风掠无影wsj"<weishaojie1995.com@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Sunwc0/vegetable_fruit_imageRe] new.train时报错 (#3)




你尝试下把batch_size调小一点试一下，inception_resnet_v2网络的输入必须是299x299大小3通道的图片，如果不是也会报错

**Comment by Sunwc0** [comment]
那个是为了放在阿里的gpu上跑，你要在自己的机器上跑就用new_train.py就行，这个issue我关了
